spring.application.name=nirnay-gov-core
server.port=8080

# Management & Health Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# DoSJE PFMS Gate Config
nirnay.dosje.ministry=Ministry of Social Justice and Empowerment
nirnay.pfms.gateway.url=https://pfms.nic.in/api/v2/disbursement-validate
nirnay.security.audit-retention-years=7
