import type {
  Project,
  Organization,
  Inspector,
  Inspection,
  CCTVCamera,
  AISignal,
  AttendanceRecord,
  DashboardMetrics,
  Notification,
  AuditEvent,
  Beneficiary,
  District,
  Scheme,
} from "@/types";

// ─────────────────────────────────────────────────────────────
// INSIGHT Demo Data — Believable Indian Government Platform Data
// All names are fictional. No real personal information.
// ─────────────────────────────────────────────────────────────

export const DEMO_DISTRICTS: District[] = [
  { id: "d1", name: "Guntur", state: "Andhra Pradesh", code: "AP-GNT", latitude: 16.3067, longitude: 80.4365, project_count: 8, active_inspections: 2 },
  { id: "d2", name: "Warangal", state: "Telangana", code: "TG-WAR", latitude: 17.9784, longitude: 79.5941, project_count: 5, active_inspections: 1 },
  { id: "d3", name: "Pune", state: "Maharashtra", code: "MH-PUN", latitude: 18.5204, longitude: 73.8567, project_count: 6, active_inspections: 2 },
  { id: "d4", name: "Bhopal", state: "Madhya Pradesh", code: "MP-BHO", latitude: 23.2599, longitude: 77.4126, project_count: 4, active_inspections: 1 },
  { id: "d5", name: "Lucknow", state: "Uttar Pradesh", code: "UP-LKO", latitude: 26.8467, longitude: 80.9462, project_count: 7, active_inspections: 3 },
  { id: "d6", name: "Jaipur", state: "Rajasthan", code: "RJ-JAI", latitude: 26.9124, longitude: 75.7873, project_count: 3, active_inspections: 1 },
  { id: "d7", name: "Coimbatore", state: "Tamil Nadu", code: "TN-CBE", latitude: 11.0168, longitude: 76.9558, project_count: 5, active_inspections: 0 },
  { id: "d8", name: "Bhubaneswar", state: "Odisha", code: "OD-BBS", latitude: 20.2961, longitude: 85.8245, project_count: 3, active_inspections: 1 },
];

export const DEMO_SCHEMES: Scheme[] = [
  { id: "s1", name: "UDID — Unique Disability ID", code: "UDID-2024", description: "Disability identification and welfare scheme", ministry: "DoSJE", is_active: true },
  { id: "s2", name: "NHFDC — Loan Scheme", code: "NHFDC-2024", description: "National Handicapped Finance and Development Corporation loans", ministry: "DoSJE", is_active: true },
  { id: "s3", name: "SIPDA — Skill Programme", code: "SIPDA-2024", description: "Skill development programme for persons with disabilities", ministry: "DoSJE", is_active: true },
  { id: "s4", name: "DDR&C — Rehabilitation", code: "DDRC-2024", description: "District Disability Rehabilitation Centre", ministry: "DoSJE", is_active: true },
  { id: "s5", name: "ADIP — Assistive Devices", code: "ADIP-2024", description: "Assistance to Disabled Persons for assistive devices", ministry: "DoSJE", is_active: true },
];

export const DEMO_ORGANIZATIONS: Organization[] = [
  { id: "o1", name: "Asha Rehabilitation Centre", type: "rehabilitation_centre", registration_number: "AP/NGO/2018/4421", district_id: "d1", district_name: "Guntur", state: "Andhra Pradesh", address: "Survey No. 42, Brodipet, Guntur - 522002", contact_name: "Dr. Ramesh Babu", contact_email: "ramesh@asharehab.org", contact_phone: "+91-9849XXXXX", scheme_ids: ["s1", "s4"], is_active: true, compliance_score: 88, created_at: "2018-06-15T00:00:00Z" },
  { id: "o2", name: "Pragati Skill Foundation", type: "skill_centre", registration_number: "TG/NGO/2019/7782", district_id: "d2", district_name: "Warangal", state: "Telangana", address: "Plot 18, Hanamkonda, Warangal - 506001", contact_name: "Mrs. Lakshmi Devi", contact_email: "lakshmi@pragatiskill.org", contact_phone: "+91-9700XXXXX", scheme_ids: ["s3"], is_active: true, compliance_score: 74, created_at: "2019-03-22T00:00:00Z" },
  { id: "o3", name: "Sahyog Institute of Inclusion", type: "institute", registration_number: "MH/NGO/2017/3310", district_id: "d3", district_name: "Pune", state: "Maharashtra", address: "Lane 7, Kothrud, Pune - 411038", contact_name: "Mr. Vivek Kulkarni", contact_email: "vivek@sahyoginclusion.org", contact_phone: "+91-9823XXXXX", scheme_ids: ["s2", "s3", "s5"], is_active: true, compliance_score: 91, created_at: "2017-09-10T00:00:00Z" },
  { id: "o4", name: "Umang District Welfare Centre", type: "welfare_centre", registration_number: "MP/NGO/2020/9901", district_id: "d4", district_name: "Bhopal", state: "Madhya Pradesh", address: "Block C, New Market, Bhopal - 462003", contact_name: "Mr. Suresh Patel", contact_email: "suresh@umangwelfare.org", contact_phone: "+91-9753XXXXX", scheme_ids: ["s1", "s2", "s4"], is_active: true, compliance_score: 62, created_at: "2020-01-05T00:00:00Z" },
  { id: "o5", name: "Hope Foundation UP", type: "ngo", registration_number: "UP/NGO/2016/1187", district_id: "d5", district_name: "Lucknow", state: "Uttar Pradesh", address: "Sector 12, Vikas Nagar, Lucknow - 226022", contact_name: "Mrs. Priya Sharma", contact_email: "priya@hopefoundationup.org", contact_phone: "+91-9415XXXXX", scheme_ids: ["s1", "s3", "s5"], is_active: true, compliance_score: 79, created_at: "2016-11-20T00:00:00Z" },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: "INS-2041",
    name: "Asha Rehabilitation Centre — Guntur",
    organization_id: "o1",
    organization_name: "Asha Rehabilitation Centre",
    district_id: "d1",
    district_name: "Guntur",
    state: "Andhra Pradesh",
    scheme_id: "s4",
    scheme_name: "DDR&C — Rehabilitation",
    status: "operational",
    location: { latitude: 16.3200, longitude: 80.4450, address: "Survey No. 42, Brodipet, Guntur - 522002", geofence_radius_meters: 200 },
    health: { overall: 86, compliance: 91, attendance: 82, inspection: 88, evidence: 93, reporting: 76, cctv: 94 },
    ai_risk_score: 18,
    registered_beneficiaries: 120,
    expected_attendance: 95,
    cctv_total: 8,
    cctv_online: 8,
    last_inspection_date: "2026-08-20T14:32:00Z",
    last_inspection_id: "INSP-0089",
    next_inspection_due: "2026-09-20T00:00:00Z",
    incharge_name: "Mr. T. Narayana Rao",
    incharge_phone: "+91-9849XXXXX",
    created_at: "2018-07-01T00:00:00Z",
    updated_at: "2026-08-20T14:32:00Z",
  },
  {
    id: "INS-2042",
    name: "Pragati Skill Centre — Warangal",
    organization_id: "o2",
    organization_name: "Pragati Skill Foundation",
    district_id: "d2",
    district_name: "Warangal",
    state: "Telangana",
    scheme_id: "s3",
    scheme_name: "SIPDA — Skill Programme",
    status: "at-risk",
    location: { latitude: 17.9900, longitude: 79.6050, address: "Plot 18, Hanamkonda, Warangal - 506001", geofence_radius_meters: 150 },
    health: { overall: 61, compliance: 68, attendance: 51, inspection: 72, evidence: 64, reporting: 58, cctv: 55 },
    ai_risk_score: 64,
    registered_beneficiaries: 85,
    expected_attendance: 70,
    cctv_total: 6,
    cctv_online: 3,
    last_inspection_date: "2026-07-14T11:20:00Z",
    last_inspection_id: "INSP-0071",
    next_inspection_due: "2026-08-28T00:00:00Z",
    incharge_name: "Mrs. Kavitha Reddy",
    incharge_phone: "+91-9700XXXXX",
    created_at: "2019-04-01T00:00:00Z",
    updated_at: "2026-08-15T09:10:00Z",
  },
  {
    id: "INS-2043",
    name: "Sahyog Institute — Pune",
    organization_id: "o3",
    organization_name: "Sahyog Institute of Inclusion",
    district_id: "d3",
    district_name: "Pune",
    state: "Maharashtra",
    scheme_id: "s3",
    scheme_name: "SIPDA — Skill Programme",
    status: "operational",
    location: { latitude: 18.5300, longitude: 73.8480, address: "Lane 7, Kothrud, Pune - 411038", geofence_radius_meters: 100 },
    health: { overall: 92, compliance: 95, attendance: 90, inspection: 92, evidence: 97, reporting: 88, cctv: 92 },
    ai_risk_score: 11,
    registered_beneficiaries: 200,
    expected_attendance: 175,
    cctv_total: 12,
    cctv_online: 12,
    last_inspection_date: "2026-08-22T10:00:00Z",
    last_inspection_id: "INSP-0091",
    next_inspection_due: "2026-09-22T00:00:00Z",
    incharge_name: "Mr. Ajay Desai",
    incharge_phone: "+91-9823XXXXX",
    created_at: "2017-10-01T00:00:00Z",
    updated_at: "2026-08-22T10:00:00Z",
  },
  {
    id: "INS-2044",
    name: "Umang Welfare Centre — Bhopal",
    organization_id: "o4",
    organization_name: "Umang District Welfare Centre",
    district_id: "d4",
    district_name: "Bhopal",
    state: "Madhya Pradesh",
    scheme_id: "s1",
    scheme_name: "UDID — Unique Disability ID",
    status: "critical",
    location: { latitude: 23.2700, longitude: 77.4200, address: "Block C, New Market, Bhopal - 462003", geofence_radius_meters: 150 },
    health: { overall: 41, compliance: 45, attendance: 34, inspection: 38, evidence: 52, reporting: 41, cctv: 36 },
    ai_risk_score: 82,
    registered_beneficiaries: 140,
    expected_attendance: 110,
    cctv_total: 10,
    cctv_online: 3,
    last_inspection_date: "2026-06-30T09:45:00Z",
    last_inspection_id: "INSP-0055",
    next_inspection_due: "2026-07-30T00:00:00Z",
    incharge_name: "Mr. Rohit Sharma",
    incharge_phone: "+91-9753XXXXX",
    created_at: "2020-02-01T00:00:00Z",
    updated_at: "2026-08-10T14:00:00Z",
  },
  {
    id: "INS-2045",
    name: "Hope Foundation — Lucknow",
    organization_id: "o5",
    organization_name: "Hope Foundation UP",
    district_id: "d5",
    district_name: "Lucknow",
    state: "Uttar Pradesh",
    scheme_id: "s5",
    scheme_name: "ADIP — Assistive Devices",
    status: "at-risk",
    location: { latitude: 26.8600, longitude: 80.9550, address: "Sector 12, Vikas Nagar, Lucknow - 226022", geofence_radius_meters: 175 },
    health: { overall: 68, compliance: 72, attendance: 59, inspection: 70, evidence: 74, reporting: 65, cctv: 68 },
    ai_risk_score: 51,
    registered_beneficiaries: 175,
    expected_attendance: 140,
    cctv_total: 8,
    cctv_online: 6,
    last_inspection_date: "2026-08-05T15:10:00Z",
    last_inspection_id: "INSP-0079",
    next_inspection_due: "2026-09-05T00:00:00Z",
    incharge_name: "Mrs. Anita Singh",
    incharge_phone: "+91-9415XXXXX",
    created_at: "2016-12-01T00:00:00Z",
    updated_at: "2026-08-05T15:10:00Z",
  },
  {
    id: "INS-2046",
    name: "Divyayan Skill Hub — Jaipur",
    organization_id: "o5",
    organization_name: "Hope Foundation UP",
    district_id: "d6",
    district_name: "Jaipur",
    state: "Rajasthan",
    scheme_id: "s3",
    scheme_name: "SIPDA — Skill Programme",
    status: "operational",
    location: { latitude: 26.9200, longitude: 75.7950, address: "Plot 22, Malviya Nagar, Jaipur - 302017", geofence_radius_meters: 150 },
    health: { overall: 78, compliance: 80, attendance: 76, inspection: 82, evidence: 79, reporting: 72, cctv: 79 },
    ai_risk_score: 34,
    registered_beneficiaries: 95,
    expected_attendance: 80,
    cctv_total: 6,
    cctv_online: 6,
    last_inspection_date: "2026-08-18T13:00:00Z",
    last_inspection_id: "INSP-0088",
    next_inspection_due: "2026-09-18T00:00:00Z",
    incharge_name: "Mr. Deepak Chauhan",
    incharge_phone: "+91-9672XXXXX",
    created_at: "2021-03-15T00:00:00Z",
    updated_at: "2026-08-18T13:00:00Z",
  },
];

export const DEMO_INSPECTORS: Inspector[] = [
  { id: "i1", name: "Officer R. Kumar", employee_id: "PMU-AP-0041", district_id: "d1", district_name: "Guntur", phone: "+91-9849XXXXX", current_workload: 2, max_workload: 5, is_available: true, is_on_leave: false, last_inspection_date: "2026-08-20T00:00:00Z", total_inspections: 47, current_latitude: 16.3100, current_longitude: 80.4300 },
  { id: "i2", name: "Officer S. Mehra", employee_id: "PMU-TG-0022", district_id: "d2", district_name: "Warangal", phone: "+91-9700XXXXX", current_workload: 3, max_workload: 5, is_available: true, is_on_leave: false, last_inspection_date: "2026-08-19T00:00:00Z", total_inspections: 62, current_latitude: 17.9750, current_longitude: 79.5900 },
  { id: "i3", name: "Officer P. Joshi", employee_id: "PMU-MH-0015", district_id: "d3", district_name: "Pune", phone: "+91-9823XXXXX", current_workload: 1, max_workload: 5, is_available: true, is_on_leave: false, last_inspection_date: "2026-08-22T00:00:00Z", total_inspections: 38, current_latitude: 18.5150, current_longitude: 73.8500 },
  { id: "i4", name: "Officer A. Tiwari", employee_id: "PMU-MP-0037", district_id: "d4", district_name: "Bhopal", phone: "+91-9753XXXXX", current_workload: 4, max_workload: 5, is_available: false, is_on_leave: false, last_inspection_date: "2026-08-25T00:00:00Z", total_inspections: 91, current_latitude: 23.2550, current_longitude: 77.4100 },
  { id: "i5", name: "Officer M. Verma", employee_id: "PMU-UP-0059", district_id: "d5", district_name: "Lucknow", phone: "+91-9415XXXXX", current_workload: 2, max_workload: 5, is_available: true, is_on_leave: false, last_inspection_date: "2026-08-23T00:00:00Z", total_inspections: 54, current_latitude: 26.8500, current_longitude: 80.9400 },
];

export const DEMO_CCTV_CAMERAS: CCTVCamera[] = [
  // INS-2041 (Guntur) — All 8 online
  { id: "cam-01", project_id: "INS-2041", camera_id: "CAM-01", label: "Main Entrance Gate", location_description: "Ground Floor — Security Entry Barrier", status: "demo", fps: 28, latency_ms: 22, last_heartbeat: new Date(Date.now() - 5000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-people-walking-in-a-building-corridor-42861-large.mp4", resolution: "1080p", connection_quality: "excellent" },
  { id: "cam-02", project_id: "INS-2041", camera_id: "CAM-02", label: "Vocational Training Lab", location_description: "Ground Floor — East Wing Skill Center", status: "demo", fps: 29, latency_ms: 18, last_heartbeat: new Date(Date.now() - 3000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-hands-of-people-working-in-a-craft-workshop-43178-large.mp4", resolution: "1080p", connection_quality: "excellent" },
  { id: "cam-03", project_id: "INS-2041", camera_id: "CAM-03", label: "Administrative Block", location_description: "First Floor — Admin & Record Office", status: "demo", fps: 25, latency_ms: 31, last_heartbeat: new Date(Date.now() - 8000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-busy-office-with-people-working-42867-large.mp4", resolution: "720p", connection_quality: "good" },
  { id: "cam-04", project_id: "INS-2041", camera_id: "CAM-04", label: "Classroom / Study Hall", location_description: "Second Floor — Digital Learning Center", status: "demo", fps: 29, latency_ms: 18, last_heartbeat: new Date(Date.now() - 2000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-students-entering-a-classroom-43177-large.mp4", resolution: "1080p", connection_quality: "excellent" },
  { id: "cam-05", project_id: "INS-2041", camera_id: "CAM-05", label: "Dining Hall & Kitchen", location_description: "Ground Floor — Meal Distribution Area", status: "demo", fps: 27, latency_ms: 25, last_heartbeat: new Date(Date.now() - 6000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-people-in-a-dining-room-42865-large.mp4", resolution: "720p", connection_quality: "good" },
  { id: "cam-06", project_id: "INS-2041", camera_id: "CAM-06", label: "Outdoor Activity Area", location_description: "Exterior — Recreational Ground", status: "demo", fps: 24, latency_ms: 38, last_heartbeat: new Date(Date.now() - 12000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-group-of-indian-friends-celebrating-3870-large.mp4", resolution: "720p", connection_quality: "good" },
  // INS-2042 (Warangal) — 3/6 online
  { id: "cam-07", project_id: "INS-2042", camera_id: "CAM-07", label: "Skill Workshop Lab 2", location_description: "Ground Floor — Practical Workshop", status: "demo", fps: 20, latency_ms: 72, last_heartbeat: new Date(Date.now() - 45000).toISOString(), demo_stream_url: "https://assets.mixkit.co/videos/preview/mixkit-students-sitting-in-a-classroom-43176-large.mp4", resolution: "480p", connection_quality: "poor" },
  { id: "cam-08", project_id: "INS-2042", camera_id: "CAM-08", label: "Main Reception", location_description: "Ground Floor — Visitor Checkpoint", status: "offline", fps: 0, latency_ms: 0, last_heartbeat: new Date(Date.now() - 840000).toISOString(), resolution: "720p", connection_quality: "none" },
  { id: "cam-09", project_id: "INS-2042", camera_id: "CAM-09", label: "Executive Office", location_description: "First Floor — Superintendent", status: "offline", fps: 0, latency_ms: 0, last_heartbeat: new Date(Date.now() - 900000).toISOString(), resolution: "720p", connection_quality: "none" },
];

export const DEMO_AI_SIGNALS: AISignal[] = [
  {
    id: "ai-001",
    project_id: "INS-2044",
    project_name: "Umang Welfare Centre — Bhopal",
    district_name: "Bhopal",
    type: "attendance_anomaly",
    severity: "critical",
    title: "Significant attendance variance detected",
    summary: "Reported attendance (64) is 51.6% higher than observed attendance (31) during last inspection.",
    explanation: {
      what_happened: "The attendance register shows 64 beneficiaries present on 15 Aug 2026. The inspection officer observed and verified only 31 individuals on site at the time of visit.",
      why_detected: "Variance between reported and observed attendance exceeded the 30% alert threshold. This pattern has recurred in 3 of the last 4 inspections.",
      data_used: ["Inspection INSP-0055 observed attendance: 31", "Submitted attendance register: 64", "Historical inspection INSP-0041 variance: 28%", "Historical inspection INSP-0047 variance: 34%"],
      confidence: 91,
      recommended_action: "Conduct an unannounced surprise inspection to verify current attendance. Cross-reference beneficiary photographs with attendance register.",
    },
    risk_score: 82,
    evidence_ids: ["ev-0041", "ev-0042"],
    is_resolved: false,
    requires_human_review: true,
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: "ai-002",
    project_id: "INS-2042",
    project_name: "Pragati Skill Centre — Warangal",
    district_name: "Warangal",
    type: "cctv_availability",
    severity: "high",
    title: "CCTV availability below threshold",
    summary: "3 of 6 cameras offline for 14+ hours. Pattern consistent with scheduled outages in prior inspection periods.",
    explanation: {
      what_happened: "CAM-08 and CAM-09 have been offline for 14 hours. These cameras cover the reception and administrative block — the areas typically reviewed during inspections.",
      why_detected: "CCTV heartbeat monitoring detected zero pings from CAM-08 and CAM-09 for >840 minutes. Cross-referencing with previous inspection schedule shows outages occurred twice before during inspection windows.",
      data_used: ["CAM-08 last heartbeat: 14h ago", "CAM-09 last heartbeat: 15h ago", "Previous outage log: 12 Jul 2026 (during INSP-0065)", "Previous outage log: 28 Jun 2026 (during INSP-0058)"],
      confidence: 78,
      recommended_action: "Initiate video verification with project incharge. Request explanation for camera unavailability. Schedule technical review.",
    },
    risk_score: 64,
    is_resolved: false,
    requires_human_review: true,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "ai-003",
    project_id: "INS-2045",
    project_name: "Hope Foundation — Lucknow",
    district_name: "Lucknow",
    type: "inspection_frequency",
    severity: "medium",
    title: "Inspection overdue by 21 days",
    summary: "Last inspection was 51 days ago. Mandated frequency is 30 days for this risk category.",
    explanation: {
      what_happened: "Project INS-2045 was last inspected on 5 Aug 2026. Based on the MEDIUM-HIGH risk classification, inspections are required every 30 days. The project is 21 days overdue.",
      why_detected: "Automated inspection schedule monitor flagged the overdue period. No exception or extension was logged for this project.",
      data_used: ["Last inspection date: 5 Aug 2026", "Mandated frequency: 30 days", "Current risk level: MEDIUM (score: 51)", "No active extension on file"],
      confidence: 99,
      recommended_action: "Assign a surprise inspection immediately. Prioritize given overdue status.",
    },
    risk_score: 51,
    is_resolved: false,
    requires_human_review: false,
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
];

export const DEMO_ATTENDANCE: AttendanceRecord[] = [
  { id: "att-1", project_id: "INS-2044", date: "2026-08-15", registered: 140, expected: 110, observed: 31, reported: 64, variance_percent: 51.6, is_anomaly: true, inspection_id: "INSP-0055" },
  { id: "att-2", project_id: "INS-2044", date: "2026-08-08", registered: 140, expected: 110, observed: 72, reported: 89, variance_percent: 19.1, is_anomaly: false },
  { id: "att-3", project_id: "INS-2044", date: "2026-08-01", registered: 140, expected: 110, observed: 45, reported: 78, variance_percent: 34.0, is_anomaly: true },
  { id: "att-4", project_id: "INS-2041", date: "2026-08-20", registered: 120, expected: 95, observed: 88, reported: 92, variance_percent: 4.2, is_anomaly: false, inspection_id: "INSP-0089" },
  { id: "att-5", project_id: "INS-2041", date: "2026-08-13", registered: 120, expected: 95, observed: 84, reported: 87, variance_percent: 3.1, is_anomaly: false },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: "n1", priority: "critical", title: "CCTV Offline — Pragati Skill Centre", message: "3 cameras offline for 14+ hours. Cameras CAM-08, CAM-09 cover inspection-critical zones.", related_project_id: "INS-2042", is_read: false, created_at: new Date(Date.now() - 840000000).toISOString(), action_url: "/projects/INS-2042/monitor" },
  { id: "n2", priority: "action_required", title: "Inspection Overdue — Hope Foundation", message: "Project INS-2045 is 21 days overdue for scheduled inspection.", related_project_id: "INS-2045", is_read: false, created_at: new Date(Date.now() - 3600000 * 6).toISOString(), action_url: "/inspections/assign" },
  { id: "n3", priority: "critical", title: "AI Anomaly — Umang Welfare Centre", message: "Attendance variance of 51.6% detected. Human verification required.", related_project_id: "INS-2044", is_read: false, created_at: new Date(Date.now() - 3600000 * 14).toISOString(), action_url: "/ai-signals/ai-001" },
  { id: "n4", priority: "information", title: "Inspection Completed — Asha Rehabilitation Centre", message: "Officer R. Kumar completed inspection INSP-0089. Report submitted.", related_project_id: "INS-2041", is_read: true, created_at: new Date(Date.now() - 3600000 * 48).toISOString() },
  { id: "n5", priority: "system", title: "System Operational", message: "All core services running normally. 12 CCTV cameras monitored.", is_read: true, created_at: new Date(Date.now() - 3600000 * 2).toISOString() },
];

export const DEMO_AUDIT_EVENTS: AuditEvent[] = [
  { id: "ae1", action: "inspection_started", actor_id: "i1", actor_name: "Officer R. Kumar", actor_role: "field_inspector", project_id: "INS-2041", inspection_id: "INSP-0089", metadata: { location: "Guntur, AP" }, timestamp: new Date(Date.now() - 3600000 * 48 + 60000 * 14).toISOString() },
  { id: "ae2", action: "gps_verified", actor_id: "i1", actor_name: "Officer R. Kumar", actor_role: "field_inspector", project_id: "INS-2041", inspection_id: "INSP-0089", metadata: { accuracy: "±6m", distance_to_project: "38m" }, timestamp: new Date(Date.now() - 3600000 * 48 + 60000 * 15).toISOString() },
  { id: "ae3", action: "evidence_captured", actor_id: "i1", actor_name: "Officer R. Kumar", actor_role: "field_inspector", project_id: "INS-2041", inspection_id: "INSP-0089", metadata: { type: "photo", count: 4 }, timestamp: new Date(Date.now() - 3600000 * 48 + 60000 * 28).toISOString() },
  { id: "ae4", action: "attendance_submitted", actor_id: "i1", actor_name: "Officer R. Kumar", actor_role: "field_inspector", project_id: "INS-2041", inspection_id: "INSP-0089", metadata: { observed: 88, reported: 92 }, timestamp: new Date(Date.now() - 3600000 * 48 + 60000 * 35).toISOString() },
  { id: "ae5", action: "report_submitted", actor_id: "i1", actor_name: "Officer R. Kumar", actor_role: "field_inspector", project_id: "INS-2041", inspection_id: "INSP-0089", metadata: { status: "compliant" }, timestamp: new Date(Date.now() - 3600000 * 48 + 60000 * 51).toISOString() },
  { id: "ae6", action: "ai_anomaly_generated", actor_id: "system", actor_name: "AI System", actor_role: "super_admin", project_id: "INS-2044", metadata: { type: "attendance_anomaly", confidence: 91 }, timestamp: new Date(Date.now() - 3600000 * 14).toISOString() },
  { id: "ae7", action: "cctv_offline", actor_id: "system", actor_name: "AI System", actor_role: "super_admin", project_id: "INS-2042", metadata: { cameras: ["CAM-08", "CAM-09"] }, timestamp: new Date(Date.now() - 840000).toISOString() },
];

export const DEMO_BENEFICIARIES: Beneficiary[] = [
  { id: "b1", project_id: "INS-2041", masked_name: "Raj•••••", program: "Physical Rehabilitation", enrollment_date: "2024-03-15", attendance_percent: 88, last_verification: "2026-08-20", services_received: ["Physiotherapy", "Assistive Device", "UDID Card"], feedback_score: 4.2, is_active: true },
  { id: "b2", project_id: "INS-2041", masked_name: "Lak•••••", program: "Vocational Training", enrollment_date: "2024-06-01", attendance_percent: 92, last_verification: "2026-08-20", services_received: ["Skill Training", "Stipend"], feedback_score: 4.5, is_active: true },
  { id: "b3", project_id: "INS-2042", masked_name: "Sur•••••", program: "Skill Development", enrollment_date: "2024-01-10", attendance_percent: 42, last_verification: "2026-08-15", services_received: ["Hardware Training"], is_active: false },
  { id: "b4", project_id: "INS-2042", masked_name: "Ani•••••", program: "Digital Literacy", enrollment_date: "2024-05-12", attendance_percent: 91, last_verification: "2026-08-18", services_received: ["Computer Skills", "Certification"], feedback_score: 4.8, is_active: true },
  { id: "b5", project_id: "INS-2043", masked_name: "Pra•••••", program: "Elderly Day Care", enrollment_date: "2023-11-20", attendance_percent: 96, last_verification: "2026-08-21", services_received: ["Geriatric Health", "Nutritional Support"], feedback_score: 4.9, is_active: true },
  { id: "b6", project_id: "INS-2044", masked_name: "Sun•••••", program: "De-addiction & Counseling", enrollment_date: "2024-08-01", attendance_percent: 54, last_verification: "2026-08-14", services_received: ["Psychological Support"], is_active: false },
];

export const DEMO_METRICS: DashboardMetrics = {
  projects_monitored: 41,
  active_inspections: 7,
  live_sites: 28,
  open_anomalies: 3,
  pending_reports: 5,
  critical_alerts: 2,
  cctv_online: 54,
  cctv_total: 68,
  inspectors_active: 12,
};

export const DEMO_INSPECTION_ACTIVE: Partial<Inspection> = {
  id: "INSP-0094",
  type: "surprise",
  status: "assigned",
  project_id: "INS-2042",
  project_name: "Pragati Skill Centre — Warangal",
  organization_name: "Pragati Skill Foundation",
  district_name: "Warangal",
  inspector_id: "i2",
  inspector_name: "Officer S. Mehra",
  current_step: "arrival",
  arrival_verified: false,
  attendance_reported: 0,
  attendance_observed: 0,
  beneficiaries_met: 0,
  evidence_ids: [],
  ai_signals: [],
  checklist_items: [
    { id: "cl-1", question: "Is the centre operating during designated hours?", category: "Operations", is_required: true },
    { id: "cl-2", question: "Are all registered beneficiaries present or accounted for?", category: "Attendance", is_required: true },
    { id: "cl-3", question: "Is attendance register maintained and up to date?", category: "Documentation", is_required: true },
    { id: "cl-4", question: "Are infrastructure facilities in proper condition?", category: "Infrastructure", is_required: true },
    { id: "cl-5", question: "Are CCTV cameras functional and recording?", category: "Security", is_required: true },
    { id: "cl-6", question: "Are qualified staff present on duty?", category: "Staffing", is_required: true },
    { id: "cl-7", question: "Are beneficiaries receiving mandated services?", category: "Services", is_required: true },
    { id: "cl-8", question: "Are medical/therapy records properly maintained?", category: "Documentation", is_required: false },
    { id: "cl-9", question: "Is emergency response protocol displayed and accessible?", category: "Safety", is_required: false },
    { id: "cl-10", question: "Are grievance redressal mechanisms in place?", category: "Governance", is_required: false },
  ],
  assigned_at: new Date(Date.now() - 3600000).toISOString(),
};
